//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuralNetIDS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NeuralNetIDS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0, 0, 0, 0, 0.5454, 0.08314, 0, 0, 0, 0.2, 0, 0.1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.001, 0.002, 0, 0, 0, 0.05, 0.1, 0, 0.1, 0.001, 0.001, 0.1, 0, 0.1, 0, 0, 0, 0, 0
        ///0, 0, 0, 0, 0.5454, 0.08314, 0, 0, 0, 0.2, 0, 0.1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.002, 0.003, 0, 0, 0, 0.033, 0.1, 0, 0.067, 0.002, 0.002, 0.1, 0, 0.05, 0, 0, 0, 0, 0
        ///0, 0, 0, 0, 0.5454, 0.08314, 0, 0, 0, 0.2, 0, 0.1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.003, 0.004, 0, 0, 0, 0.025, 0.1, 0, 0.05, 0.003, 0.003, 0.1, 0, 0.033, 0, 0, 0, 0, 0
        ///0,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BackDoor {
            get {
                return ResourceManager.GetString("BackDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0023, 0, 0.05, 0, 0.00104, 0.00276, 0, 0, 0, 0, 0.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.001, 0.001, 0, 0, 0, 0, 0.1, 0, 0, 0.001, 0.002, 0.1, 0, 0.1, 0.1, 0, 0, 0, 0
        ///0.006, 0, 0.05, 0.03, 0.00125, 0.00179, 0, 0, 0, 0.1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.001, 0.001, 0.1, 0.1, 0, 0, 0.1, 0, 0, 0.001, 0.001, 0.1, 0, 0.1, 0, 0.1, 0.1, 0, 0
        ///0, 0, 0.05, 0.06, 0.00125, 0.00179, 0, 0, 0, 0.1, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.002, 0.002, 0.05, 0.05, 0.05, 0.05, 0.1, 0, 0, 0.002, 0.002, 0.1, 0, 0.05, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GuessPassword {
            get {
                return ResourceManager.GetString("GuessPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0, 0, 0, 0, 0.00215, 0.45076, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.001, 0.001, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        ///0, 0, 0, 0, 0.00162, 0.04528, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.002, 0.002, 0, 0, 0, 0, 0.1, 0, 0, 0.001, 0.001, 0.1, 0, 0.1, 0, 0, 0, 0, 0
        ///0, 0, 0, 0, 0.00236, 0.01228, 0, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.001, 0.001, 0, 0, 0, 0, 0.1, 0, 0, 0.002, 0.002, 0.1, 0, 0.05, 0, 0, 0, 0, 0
        ///0, 0, 0, 0, 0.00233, 0.02032, 0, 0, 0, 0, 0, 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.006, 0, 0.05, 0, 0.00086, 0.00183, 0, 0, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.001, 0.001, 0, 0, 0, 0, 0.1, 0, 0, 0.255, 0.001, 0, 0.002, 0, 0, 0, 0, 0, 0
        ///0.006, 0, 0.05, 0, 0.0009, 0.00233, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.001, 0.001, 0, 0, 0, 0, 0.1, 0, 0, 0.255, 0.002, 0.001, 0.002, 0, 0, 0, 0, 0, 0
        ///0.0708, 0, 0.05, 0, 0.01727, 0.2408, 0, 0, 0, 0, 0, 0.1, 0.6, 0, 0, 0.7, 0, 0, 0, 0, 0, 0, 0.001, 0.001, 0, 0, 0, 0, 0.1, 0, 0, 0.255, 0.003, 0.001, 0.002, 0, 0, 0, 0, 0, 0
        ///0.002 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RootKit {
            get {
                return ResourceManager.GetString("RootKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0, 0.02, 0.09, 0, 0.01032, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.001, 0.001, 0, 0, 0, 0, 0.1, 0, 0, 0.146, 0.001, 0.001, 0.002, 0.001, 0, 0, 0, 0, 0
        ///0, 0.02, 0.09, 0, 0.01032, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.315, 0.315, 0, 0, 0, 0, 0.1, 0, 0, 0.147, 0.002, 0.001, 0.002, 0.001, 0, 0, 0, 0, 0
        ///0, 0.02, 0.09, 0, 0.01032, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.316, 0.316, 0, 0, 0, 0, 0.1, 0, 0, 0.148, 0.003, 0.002, 0.002, 0.002, 0, 0, 0, 0, 0
        ///0, 0.02, 0.09, 0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Smurf {
            get {
                return ResourceManager.GetString("Smurf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0, 0.01, 0.12, 0, 0.00028, 0, 0, 0.1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.001, 0.001, 0, 0, 0, 0, 0.1, 0, 0, 0.073, 0.001, 0.001, 0.005, 0.001, 0, 0, 0, 0, 0
        ///0, 0.01, 0.12, 0, 0.00028, 0, 0, 0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.002, 0.002, 0, 0, 0, 0, 0.1, 0, 0, 0.074, 0.002, 0.003, 0.005, 0.003, 0, 0, 0, 0, 0
        ///0, 0.01, 0.12, 0, 0.00028, 0, 0, 0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.003, 0.003, 0, 0, 0, 0, 0.1, 0, 0, 0.075, 0.003, 0.004, 0.005, 0.004, 0, 0, 0, 0, 0
        ///0, 0.01, 0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TearDrop {
            get {
                return ResourceManager.GetString("TearDrop", resourceCulture);
            }
        }
    }
}
